##======================================================================================================================
##  RABERU - Fancy Named Parameter Library
##  Copyright : RABERU Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: RABERU Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    permissions:
      contents: write
    uses: jfalcou/copacabana/.github/workflows/documentation.yml@3337f916bb581d0829909976773f7a2ee827a25c # v4
    with:
      project: raberu
      coverage: true
